[package]
name = "Tarea-Corta-1-Operativos"
version = "0.1.0"
authors = ["Danny <Danny250297@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
